spring:
  application:
    name: security
#  security:
#    user:
#      name: raji
#      password: raji123

  datasource:
    url: jdbc:mysql://localhost:3306/app_db?&jdbcCompliantTruncation=false
    username: app_user
    password: app_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: validate
        format_sql: true
    show-sql: true
    database-platform: org.hib ernate.dialect.MySQLDialect